version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    groups:
      docusaurus:
        patterns:
          - '@docusaurus*'
