name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 8
          cache: 'maven'
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - name: Check formatting
        run: |
          npm ci
          npm run prettier:check
      - name: Build
        run: mvn --no-transfer-progress --batch-mode clean verify

  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Build
        working-directory: website
        run: |
          yarn install
          yarn build

  liquibase-compatibility:
    runs-on: ubuntu-latest
    needs: [build, build-website]
    strategy:
      matrix:
        liquibase-minor-version:
          - '4.23'
          - '4.33'
          - '5.0'
        include:
          - yaml-version: '2.3'
          - java-version: 8
          - liquibase-minor-version: '4.23'
            yaml-version: '2.0'
          - liquibase-minor-version: '5.0'
            java-version: 17
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - name: Setup semver tool
        run: npm install -g semver
      - name: Run Liquibase compatibility tests for liquibase version ${{ matrix.liquibase-minor-version }}
        run: >
          LIQUIBASE_NEXT_MINOR_VERSION=$(semver ${{ matrix.liquibase-minor-version }}.0 --increment minor);
          LIQUIBASE_VERSION_RANGE="[${{ matrix.liquibase-minor-version }}.0,${LIQUIBASE_NEXT_MINOR_VERSION})";
          echo "Liquibase version range: ${LIQUIBASE_VERSION_RANGE}";
          mvn clean verify --no-transfer-progress --batch-mode -Dliquibase.version="${LIQUIBASE_VERSION_RANGE}" -Dyaml.version="${{ matrix.yaml-version }}"
