name: Codeberg mirroring

on:
  schedule:
    - cron: '59 * * * *'

permissions:
  contents: read

concurrency:
  group: codeberg-mirroring-group

jobs:
  mirror:
    name: Mirror repo
    runs-on: ubuntu-latest
    if: github.repository == 'liquibase-linter/liquibase-linter'
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - uses: yesolutions/mirror-action@1708f16cdb28634fd3ba10c5c79abc91f5578a14 # v0.7.0
        id: mirror
        continue-on-error: true
        with:
          REMOTE: git@codeberg.org:liquibase-linter/liquibase-linter.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_SSH_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.CODEBERG_KNOWN_HOSTS }}
      - name: Log success
        if: steps.mirror.outcome == 'success'
        run: echo "Successfully mirrored to Codeberg"
